---
# COPY this file to secrets.yml
development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: <use `rake newkey:db` to generate a secret key>

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: <use `rake newkey:db` to generate a secret key>

production:
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
