---
# COPY this file to secrets.yml
development:
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP

test:
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP

production:
  MSG_KEY: <use `rake newkey:msg` to generate a secret key>
  DATABASE_URL: <set to production DB>
  DB_KEY: <use `rake newkey:db` to generate a secret key>
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTPS
